### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by filleduchaos** [filleduchaos/dart-bindgen#2]
- [ ] Rewrite README for initial release
- [ ] Update changelog for initial release
- [ ] Add dartdocs for all public-facing APIs
- [ ] Extend CLI usage notes
- [ ] Write and publish basic user guide
- [ ] Set up "gallery" of samples (backed by Github Gists?)
