### ISSUE TITLE
Idiomatic Dart representations

### ISSUE THREAD

**Issue by filleduchaos** [filleduchaos/dart-bindgen#20]
Tracks all types that can/should be automatically converted back and forth from C to corresponding idiomatic Dart types (see #8)

- [x] Booleans (`bool` <-> `bool`)
- [x] Strings (`char *` <-> `String`)
- [x] Enums (`enum Foo` <-> `enum Foo` or `class Foo`)
- [ ] Timestamp (`time_t` <-> `DateTime`)
