### ISSUE TITLE
Configurability and flexibility enhancements

### ISSUE THREAD

**Issue by filleduchaos** [filleduchaos/dart-bindgen#22]
Tracks issues for exposing more of the parsing/code generation process to users.

- [ ] YAML config (#7)
- [ ] Customize function lookup (#6)
- [ ] [Clang] Specify files to be included/excluded
- [ ] [Clang] Specify declarations to be included/excluded
